name = "BeastUtils"
uuid = "af749cb1-4ea1-40dc-96cd-a9902a2c5721"
authors = ["Gabe Hassler <gabriel.w.hassler@gmail.com>"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
